// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ErrorPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"d-flex flex-column justify-content-center align-items-center vh-100 overflow-y-auto gradient-bottom-right start-indigo middle-yellow end-purple\"><div class=\"container-xxl\"><div class=\"row justify-content-center align-items-center\"><div class=\"col-lg-6 text-center h-100 order-lg-2\"></div><div class=\"col-lg-4 order-lg-1\"><div class=\"\"><h1 class=\"display-1 mb-4\">Ooops!</h1><p class=\"lead lh-relaxed\">The page you are looking for could not be found.</p><div class=\"my-10\"><a href=\"/pages/dashboard.html\" class=\"btn btn-dark\">Return Home</a></div><div class=\"vstack gap-5 w-lg-88\"><div class=\"\"><a href=\"\" class=\"h5 text-heading text-primary-hover\">Documentation<i class=\"far fa-arrow-right ms-2\"></i></a><p class=\"text-sm\">Everything you need to know is here.</p></div><div class=\"\"><a href=\"\" class=\"h5 text-heading text-primary-hover\">Browse components<i class=\"far fa-arrow-right ms-2\"></i></a><p class=\"text-sm\">Copy and paste UI snippets fast and easy.</p></div><div class=\"\"><a href=\"\" class=\"h5 text-heading text-primary-hover\">Get our support<i class=\"far fa-arrow-right ms-2\"></i></a><p class=\"text-sm\">Check out our communication channels.</p></div></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
