// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PaginationControl() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"py-4 px-6\"><div class=\"row align-items-center justify-content-between\"><div class=\"col-md-6 d-none d-md-block\"><span class=\"text-muted text-sm\">Showing <span x-text=\"currentPageEnd\"></span> of <span x-text=\"totalItems\"></span> results</span></div><div class=\"col-md-auto\"><nav aria-label=\"Page navigation example\"><ul class=\"pagination pagination-spaced gap-1\"><!-- First Page Button --><li class=\"page-item\" :class=\"{&#39;disabled&#39;: currentPage === 1}\"><a class=\"page-link\" href=\"#\" @click.prevent=\"changePage(1)\"><i class=\"bi bi-chevron-double-left\"></i></a></li><!-- Previous Page Button --><li class=\"page-item\" :class=\"{&#39;disabled&#39;: currentPage === 1}\"><a class=\"page-link\" href=\"#\" @click.prevent=\"changePage(currentPage - 1)\"><i class=\"bi bi-chevron-left\"></i></a></li><!-- Page Number Buttons --><template x-for=\"page in pageNumbers\" :key=\"page\"><li class=\"page-item\" :class=\"{&#39;active&#39;: currentPage === page}\"><a class=\"page-link\" href=\"#\" @click.prevent=\"changePage(page)\" x-text=\"page\"></a></li></template><!-- Next Page Button --><li class=\"page-item\" :class=\"{&#39;disabled&#39;: currentPage === totalPages}\"><a class=\"page-link\" href=\"#\" @click.prevent=\"changePage(currentPage + 1)\"><i class=\"bi bi-chevron-right\"></i></a></li><!-- Last Page Button --><li class=\"page-item\" :class=\"{&#39;disabled&#39;: currentPage === totalPages}\"><a class=\"page-link\" href=\"#\" @click.prevent=\"changePage(totalPages)\"><i class=\"bi bi-chevron-double-right\"></i></a></li></ul></nav></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
